
var vimType = vm.vimType;
var overallCpuUsage = vm.overallCpuUsage;
var memory = vm.memory;
var vimId = vm.vimId;
var instanceId = vm.instanceId;
var hostMemoryUsage = vm.hostMemoryUsage;
var guestMemoryUsage = vm.guestMemoryUsage;
var vmToolsVersionStatus = vm.vmToolsVersionStatus;
var biosid = vm.biosid;
var productVendor = vm.productVendor;
var isTemplate = vm.isTemplate;
var vmToolsStatus = vm.vmToolsStatus;
var name = vm.name;
var displayName = vm.displayName;
var unsharedStorage = vm.unsharedStorage;
var id = vm.id;
var cpu = vm.cpu;
var connection = vm.connection;
var vcHostname = vm.hostName;
var type = vm.type;
var sdkId = vm.sdkId;
var guestHeartbeatStatus = vm.guestHeartbeatStatus;
var overallStatus = vm.overallStatus;
var totalStorage = vm.totalStorage;
var guestOS = vm.guestOS;
var productFullVersion = vm.productFullVersion;
var configStatus = vm.configStatus;
var ipAddress = vm.ipAddress;
var annotation = vm.annotation;
var productName = vm.productName;
var power = vm.state;
var mem = vm.mem;
var memoryOverhead = vm.memoryOverhead;
var alarmActionsEnabled = vm.alarmActionsEnabled;
var vmVersion = vm.vmVersion;



System.log('\n' + 'Start VC:VirtualMachine Logs');
System.log('name' + '  ->  '+ name);
System.log('displayName' + '  ->  '+ displayName);
System.log('hostname' + '  ->  '+ vcHostname);
System.log('vimId' + '  ->  '+ vimId);
System.log('instanceId' + '  ->  '+ instanceId);
System.log('state' + '  ->  '+ power);
System.log('vmTools' + '  ->  '+ vmToolsVersionStatus);
System.log('id' + '  ->  '+ id);
System.log('cpu'+ '  ->  '+ cpu);
System.log('ipAddress'+ '  ->  '+ ipAddress);
System.log('sdkId'+ '  ->  '+ sdkId);
System.log('totalStorage'+ '  ->  '+ totalStorage);
System.log('vmVersion' + '  ->  '+ vmVersion);
System.log('guestOS'+ '  ->  '+ guestOS);
System.log('vimType' + '  ->  '+ vimType);
System.log('overallCpuUsage' + '  ->  '+ overallCpuUsage);
System.log('memory' + '  ->  '+ memory);
System.log('hostMemoryUsage' + '  ->  '+ hostMemoryUsage);
System.log('guestMemoryUsage' + '  ->  '+ guestMemoryUsage);
System.log('biosid' + '  ->  '+ biosid);
System.log('productVendor' + '  ->  '+ productVendor);
System.log('isTemplate' + '  +  '+ isTemplate);
System.log('vmToolsStatus' + '  ->  '+ vmToolsStatus);
System.log('unsharedStorage' + '  ->  '+ unsharedStorage);
System.log('type' + '  ->  '+ type);
System.log('guestHeartbeatStatus' + '  ->  '+ guestHeartbeatStatus);
System.log('overallStatus' + '  ->  '+ overallStatus);
System.log('productFullVersion' + '  ->  '+ productFullVersion);
System.log('configStatus' + '  ->  '+ configStatus);
System.log('annotation' + '  ->  '+ annotation);
System.log('productName' + '  ->  '+ productName);
System.log('mem' + '  ->  '+ mem);
System.log('memoryOverhead' + '  ->  '+ memoryOverhead);
System.log('alarmActionsEnabled' + '  ->  '+ alarmActionsEnabled);
System.log('\n' + "End VC:VirtualMachine Logs");
